// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYR5s9QLK_f0WrRYJIt-xH88s5_tfiw2k',
    appId: '1:521884876312:web:f187638af078aefbdc8d6d',
    messagingSenderId: '521884876312',
    projectId: 'my-expenses-ba972',
    authDomain: 'my-expenses-ba972.firebaseapp.com',
    storageBucket: 'my-expenses-ba972.appspot.com',
    measurementId: 'G-LWG5WD8NY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIpBvQi-JTdPWMJ2ce4lR4jKCPclQ8xYc',
    appId: '1:521884876312:android:6982c5c498910240dc8d6d',
    messagingSenderId: '521884876312',
    projectId: 'my-expenses-ba972',
    storageBucket: 'my-expenses-ba972.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvGdGMqK_6EWyK5t9u4fGL1Z7qGBrUmnQ',
    appId: '1:521884876312:ios:0f6c010e5b26cc28dc8d6d',
    messagingSenderId: '521884876312',
    projectId: 'my-expenses-ba972',
    storageBucket: 'my-expenses-ba972.appspot.com',
    iosClientId:
        '521884876312-khe681739clcl8kh7aap393tah9ckn26.apps.googleusercontent.com',
    iosBundleId: 'com.mastertipsy.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvGdGMqK_6EWyK5t9u4fGL1Z7qGBrUmnQ',
    appId: '1:521884876312:ios:0f6c010e5b26cc28dc8d6d',
    messagingSenderId: '521884876312',
    projectId: 'my-expenses-ba972',
    storageBucket: 'my-expenses-ba972.appspot.com',
    iosClientId:
        '521884876312-khe681739clcl8kh7aap393tah9ckn26.apps.googleusercontent.com',
    iosBundleId: 'com.mastertipsy.expenses',
  );
}
